// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poqsauhwspmwkwiqxbqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvcXNhdWh3c3Btd2t3aXF4YnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MTI1NDksImV4cCI6MjA1MzQ4ODU0OX0.cJQaEdoqx-quYBwWJjzimtBlbqfyhI0v88mSfL6qK80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);